# https://docs.npmjs.com/trusted-publishers
name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Version bump
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
          node-version: "24.x"

      - name: Bump version
        run: pnpm version ${{ inputs.bump }} -m "v%s"

      - run: pnpm install --frozen-lockfile

      - name: Publish to NPM
        run: pnpm publish --no-git-checks --access public

      - name: Push
        run: git push --follow-tags
